### ISSUE TITLE
Firebase config in clear text

### ISSUE THREAD

**Issue by w3bdesign** [phalbert/crown-fashion#1]
Hi @phalbert 

Just wanted to let you know that in  crown-clothing/src/firebase/firebase.utils.js you should move the config object to a .ENV file for local development and load the information in production by setting environment variables in Heroku/Netlify etc. 
This is for security reasons so that nobody can access your configuration settings.

You can create a .ENV file with the following (you need to set the environment variables manually in Heroku/Netlify etc as your .ENV should be in your .gitignore and will not be uploaded):

```
REACT_APP_APIKEY=INSERT THIS FROM GOOGLE
REACT_APP_AUTH_DOMAIN=INSERT THIS FROM GOOGLE
REACT_APP_DATABASEURL=INSERT THIS FROM GOOGLE
REACT_APP_PROJECTID=INSERT THIS FROM GOOGLE
REACT_APP_STORAGEBUCKET=INSERT THIS FROM GOOGLE
REACT_APP_MESSAGINGSENDERID=INSERT THIS FROM GOOGLE
REACT_APP_APPID=INSERT THIS FROM GOOGLE
REACT_APP_MEASUREMENTID=INSERT THIS FROM GOOGLE
```

Then in your firebase.utils.js you can modify the config object to this:

```
const config = {
  apiKey: process.env.REACT_APP_APIKEY,
  authDomain: process.env.REACT_APP_AUTH_DOMAIN,
  databaseURL: process.env.REACT_APP_DATABASEURL,
  projectId: process.env.REACT_APP_PROJECTID,
  storageBucket: process.env.REACT_APP_STORAGEBUCKET,
  messagingSenderId: process.env.REACT_APP_MESSAGINGSENDERID,
  appId: process.env.REACT_APP_APPID,
  measurementId: process.env.REACT_APP_MEASUREMENTID
};
```

Let me know if anything is unclear!

**Comment by phalbert** [comment]
@w3bdesign, thank you for pointing this out. let me fix it

**Comment by w3bdesign** [comment]
@phalbert Just to let you know, .ENV support is built into React if you use Create React App, which I assume you already use, so you do not need to install any extra packages.

For reference, I highly recommend that you read https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by phalbert** [comment]
@w3bdesign, I have removed the file from all previous commits. I am now using the builtin .env support too. Do check this and let me know if it's good now

**Comment by w3bdesign** [comment]
> 
> 
> @w3bdesign, I have removed the file from all previous commits. I am now using the builtin .env support too. Do check this and let me know if it's good now

Looks good now @phalbert .

By the way, how did you remove the information from the commit log?

**Comment by phalbert** [comment]
I used `git filter-branch` by following this [answer](https://stackoverflow.com/questions/872565/remove-sensitive-files-and-their-commits-from-git-history)
